version: '3'

tasks:
  fmt:
    desc: Format Zig code using zig fmt
    cmds:
      - zig fmt src/

  test:
    desc: Run tests using zig build test
    cmds:
      - zig build test

  build:
    desc: Build the project using zig build
    deps: [fmt]
    cmds:
      - zig build

  check:
    desc: Run format check and tests without modifying files
    cmds:
      - zig fmt --check src/
      - zig build test

  clean:
    desc: Clean the build directory
    cmds:
      - zig build clean
